package com.offcn.dao;

import com.offcn.pojo.admin;
import com.offcn.pojo.adminExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface adminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    int countByExample(adminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    int deleteByExample(adminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    int deleteByPrimaryKey(Long aId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    int insert(admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    int insertSelective(admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    List<admin> selectByExample(adminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    admin selectByPrimaryKey(Integer aId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    int updateByExampleSelective(@Param("record") admin record, @Param("example") adminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    int updateByExample(@Param("record") admin record, @Param("example") adminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    int updateByPrimaryKeySelective(admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    int updateByPrimaryKey(admin record);
}