package com.offcn.dao;

import com.offcn.pojo.conditions;
import com.offcn.pojo.conditionsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface conditionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conditions
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    int countByExample(conditionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conditions
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    int deleteByExample(conditionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conditions
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    int deleteByPrimaryKey(Long conId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conditions
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    int insert(conditions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conditions
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    int insertSelective(conditions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conditions
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    List<conditions> selectByExample(conditionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conditions
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    conditions selectByPrimaryKey(Integer conId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conditions
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    int updateByExampleSelective(@Param("record") conditions record, @Param("example") conditionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conditions
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    int updateByExample(@Param("record") conditions record, @Param("example") conditionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conditions
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    int updateByPrimaryKeySelective(conditions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conditions
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    int updateByPrimaryKey(conditions record);
}