package com.offcn.dao;

import com.offcn.pojo.staff;
import com.offcn.pojo.staffExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface staffMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    int countByExample(staffExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    int deleteByExample(staffExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    int deleteByPrimaryKey(Long staffId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    int insert(staff record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    int insertSelective(staff record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    List<staff> selectByExample(staffExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    staff selectByPrimaryKey(Integer staffId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    int updateByExampleSelective(@Param("record") staff record, @Param("example") staffExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    int updateByExample(@Param("record") staff record, @Param("example") staffExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    int updateByPrimaryKeySelective(staff record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    int updateByPrimaryKey(staff record);
}