package com.offcn.dao;

import com.offcn.pojo.waybill;
import com.offcn.pojo.waybillExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface waybillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waybill
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    int countByExample(waybillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waybill
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    int deleteByExample(waybillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waybill
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    int deleteByPrimaryKey(String waybillId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waybill
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    int insert(waybill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waybill
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    int insertSelective(waybill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waybill
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    List<waybill> selectByExample(waybillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waybill
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    waybill selectByPrimaryKey(String waybillId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waybill
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    int updateByExampleSelective(@Param("record") waybill record, @Param("example") waybillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waybill
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    int updateByExample(@Param("record") waybill record, @Param("example") waybillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waybill
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    int updateByPrimaryKeySelective(waybill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waybill
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    int updateByPrimaryKey(waybill record);
}