package com.offcn.pojo;

public class admin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.a_id
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    private Integer aId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.a_account
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    private String aAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.a_password
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    private String aPassword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.a_id
     *
     * @return the value of admin.a_id
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public Integer getaId() {
        return aId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.a_id
     *
     * @param aId the value for admin.a_id
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public void setaId(Integer aId) {
        this.aId = aId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.a_account
     *
     * @return the value of admin.a_account
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public String getaAccount() {
        return aAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.a_account
     *
     * @param aAccount the value for admin.a_account
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public void setaAccount(String aAccount) {
        this.aAccount = aAccount == null ? null : aAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.a_password
     *
     * @return the value of admin.a_password
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public String getaPassword() {
        return aPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.a_password
     *
     * @param aPassword the value for admin.a_password
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public void setaPassword(String aPassword) {
        this.aPassword = aPassword == null ? null : aPassword.trim();
    }
}