package com.offcn.pojo;

import java.util.Date;




public class conditions {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conditions.con_id
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    private Integer conId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conditions.waybill_id
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    private String waybillId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conditions.c_time
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    private Date cTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conditions.c_position
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    private String cPosition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conditions.c_express
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
  
    private String cExpress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conditions.con_id
     *
     * @return the value of conditions.con_id
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public Integer getConId() {
        return conId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conditions.con_id
     *
     * @param conId the value for conditions.con_id
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public void setConId(Integer conId) {
        this.conId = conId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conditions.waybill_id
     *
     * @return the value of conditions.waybill_id
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public String getWaybillId() {
        return waybillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conditions.waybill_id
     *
     * @param waybillId the value for conditions.waybill_id
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public void setWaybillId(String waybillId) {
        this.waybillId = waybillId == null ? null : waybillId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conditions.c_time
     *
     * @return the value of conditions.c_time
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public Date getcTime() {
        return cTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conditions.c_time
     *
     * @param cTime the value for conditions.c_time
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public void setcTime(Date cTime) {
        this.cTime = cTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conditions.c_position
     *
     * @return the value of conditions.c_position
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public String getcPosition() {
        return cPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conditions.c_position
     *
     * @param cPosition the value for conditions.c_position
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public void setcPosition(String cPosition) {
        this.cPosition = cPosition == null ? null : cPosition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conditions.c_express
     *
     * @return the value of conditions.c_express
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public String getcExpress() {
        return cExpress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conditions.c_express
     *
     * @param cExpress the value for conditions.c_express
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public void setcExpress(String cExpress) {
        this.cExpress = cExpress == null ? null : cExpress.trim();
    }
}