package com.offcn.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class conditionsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table conditions
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table conditions
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table conditions
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conditions
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public conditionsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conditions
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conditions
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conditions
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conditions
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conditions
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conditions
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conditions
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conditions
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conditions
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conditions
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table conditions
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andConIdIsNull() {
            addCriterion("con_id is null");
            return (Criteria) this;
        }

        public Criteria andConIdIsNotNull() {
            addCriterion("con_id is not null");
            return (Criteria) this;
        }

        public Criteria andConIdEqualTo(Integer value) {
            addCriterion("con_id =", value, "conId");
            return (Criteria) this;
        }

        public Criteria andConIdNotEqualTo(Integer value) {
            addCriterion("con_id <>", value, "conId");
            return (Criteria) this;
        }

        public Criteria andConIdGreaterThan(Integer value) {
            addCriterion("con_id >", value, "conId");
            return (Criteria) this;
        }

        public Criteria andConIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("con_id >=", value, "conId");
            return (Criteria) this;
        }

        public Criteria andConIdLessThan(Integer value) {
            addCriterion("con_id <", value, "conId");
            return (Criteria) this;
        }

        public Criteria andConIdLessThanOrEqualTo(Integer value) {
            addCriterion("con_id <=", value, "conId");
            return (Criteria) this;
        }

        public Criteria andConIdIn(List<Integer> values) {
            addCriterion("con_id in", values, "conId");
            return (Criteria) this;
        }

        public Criteria andConIdNotIn(List<Integer> values) {
            addCriterion("con_id not in", values, "conId");
            return (Criteria) this;
        }

        public Criteria andConIdBetween(Integer value1, Integer value2) {
            addCriterion("con_id between", value1, value2, "conId");
            return (Criteria) this;
        }

        public Criteria andConIdNotBetween(Integer value1, Integer value2) {
            addCriterion("con_id not between", value1, value2, "conId");
            return (Criteria) this;
        }

        public Criteria andWaybillIdIsNull() {
            addCriterion("waybill_id is null");
            return (Criteria) this;
        }

        public Criteria andWaybillIdIsNotNull() {
            addCriterion("waybill_id is not null");
            return (Criteria) this;
        }

        public Criteria andWaybillIdEqualTo(String value) {
            addCriterion("waybill_id =", value, "waybillId");
            return (Criteria) this;
        }

        public Criteria andWaybillIdNotEqualTo(String value) {
            addCriterion("waybill_id <>", value, "waybillId");
            return (Criteria) this;
        }

        public Criteria andWaybillIdGreaterThan(String value) {
            addCriterion("waybill_id >", value, "waybillId");
            return (Criteria) this;
        }

        public Criteria andWaybillIdGreaterThanOrEqualTo(String value) {
            addCriterion("waybill_id >=", value, "waybillId");
            return (Criteria) this;
        }

        public Criteria andWaybillIdLessThan(String value) {
            addCriterion("waybill_id <", value, "waybillId");
            return (Criteria) this;
        }

        public Criteria andWaybillIdLessThanOrEqualTo(String value) {
            addCriterion("waybill_id <=", value, "waybillId");
            return (Criteria) this;
        }

        public Criteria andWaybillIdLike(String value) {
            addCriterion("waybill_id like", value, "waybillId");
            return (Criteria) this;
        }

        public Criteria andWaybillIdNotLike(String value) {
            addCriterion("waybill_id not like", value, "waybillId");
            return (Criteria) this;
        }

        public Criteria andWaybillIdIn(List<String> values) {
            addCriterion("waybill_id in", values, "waybillId");
            return (Criteria) this;
        }

        public Criteria andWaybillIdNotIn(List<String> values) {
            addCriterion("waybill_id not in", values, "waybillId");
            return (Criteria) this;
        }

        public Criteria andWaybillIdBetween(String value1, String value2) {
            addCriterion("waybill_id between", value1, value2, "waybillId");
            return (Criteria) this;
        }

        public Criteria andWaybillIdNotBetween(String value1, String value2) {
            addCriterion("waybill_id not between", value1, value2, "waybillId");
            return (Criteria) this;
        }

        public Criteria andCTimeIsNull() {
            addCriterion("c_time is null");
            return (Criteria) this;
        }

        public Criteria andCTimeIsNotNull() {
            addCriterion("c_time is not null");
            return (Criteria) this;
        }

        public Criteria andCTimeEqualTo(Date value) {
            addCriterion("c_time =", value, "cTime");
            return (Criteria) this;
        }

        public Criteria andCTimeNotEqualTo(Date value) {
            addCriterion("c_time <>", value, "cTime");
            return (Criteria) this;
        }

        public Criteria andCTimeGreaterThan(Date value) {
            addCriterion("c_time >", value, "cTime");
            return (Criteria) this;
        }

        public Criteria andCTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("c_time >=", value, "cTime");
            return (Criteria) this;
        }

        public Criteria andCTimeLessThan(Date value) {
            addCriterion("c_time <", value, "cTime");
            return (Criteria) this;
        }

        public Criteria andCTimeLessThanOrEqualTo(Date value) {
            addCriterion("c_time <=", value, "cTime");
            return (Criteria) this;
        }

        public Criteria andCTimeIn(List<Date> values) {
            addCriterion("c_time in", values, "cTime");
            return (Criteria) this;
        }

        public Criteria andCTimeNotIn(List<Date> values) {
            addCriterion("c_time not in", values, "cTime");
            return (Criteria) this;
        }

        public Criteria andCTimeBetween(Date value1, Date value2) {
            addCriterion("c_time between", value1, value2, "cTime");
            return (Criteria) this;
        }

        public Criteria andCTimeNotBetween(Date value1, Date value2) {
            addCriterion("c_time not between", value1, value2, "cTime");
            return (Criteria) this;
        }

        public Criteria andCPositionIsNull() {
            addCriterion("c_position is null");
            return (Criteria) this;
        }

        public Criteria andCPositionIsNotNull() {
            addCriterion("c_position is not null");
            return (Criteria) this;
        }

        public Criteria andCPositionEqualTo(String value) {
            addCriterion("c_position =", value, "cPosition");
            return (Criteria) this;
        }

        public Criteria andCPositionNotEqualTo(String value) {
            addCriterion("c_position <>", value, "cPosition");
            return (Criteria) this;
        }

        public Criteria andCPositionGreaterThan(String value) {
            addCriterion("c_position >", value, "cPosition");
            return (Criteria) this;
        }

        public Criteria andCPositionGreaterThanOrEqualTo(String value) {
            addCriterion("c_position >=", value, "cPosition");
            return (Criteria) this;
        }

        public Criteria andCPositionLessThan(String value) {
            addCriterion("c_position <", value, "cPosition");
            return (Criteria) this;
        }

        public Criteria andCPositionLessThanOrEqualTo(String value) {
            addCriterion("c_position <=", value, "cPosition");
            return (Criteria) this;
        }

        public Criteria andCPositionLike(String value) {
            addCriterion("c_position like", value, "cPosition");
            return (Criteria) this;
        }

        public Criteria andCPositionNotLike(String value) {
            addCriterion("c_position not like", value, "cPosition");
            return (Criteria) this;
        }

        public Criteria andCPositionIn(List<String> values) {
            addCriterion("c_position in", values, "cPosition");
            return (Criteria) this;
        }

        public Criteria andCPositionNotIn(List<String> values) {
            addCriterion("c_position not in", values, "cPosition");
            return (Criteria) this;
        }

        public Criteria andCPositionBetween(String value1, String value2) {
            addCriterion("c_position between", value1, value2, "cPosition");
            return (Criteria) this;
        }

        public Criteria andCPositionNotBetween(String value1, String value2) {
            addCriterion("c_position not between", value1, value2, "cPosition");
            return (Criteria) this;
        }

        public Criteria andCExpressIsNull() {
            addCriterion("c_express is null");
            return (Criteria) this;
        }

        public Criteria andCExpressIsNotNull() {
            addCriterion("c_express is not null");
            return (Criteria) this;
        }

        public Criteria andCExpressEqualTo(String value) {
            addCriterion("c_express =", value, "cExpress");
            return (Criteria) this;
        }

        public Criteria andCExpressNotEqualTo(String value) {
            addCriterion("c_express <>", value, "cExpress");
            return (Criteria) this;
        }

        public Criteria andCExpressGreaterThan(String value) {
            addCriterion("c_express >", value, "cExpress");
            return (Criteria) this;
        }

        public Criteria andCExpressGreaterThanOrEqualTo(String value) {
            addCriterion("c_express >=", value, "cExpress");
            return (Criteria) this;
        }

        public Criteria andCExpressLessThan(String value) {
            addCriterion("c_express <", value, "cExpress");
            return (Criteria) this;
        }

        public Criteria andCExpressLessThanOrEqualTo(String value) {
            addCriterion("c_express <=", value, "cExpress");
            return (Criteria) this;
        }

        public Criteria andCExpressLike(String value) {
            addCriterion("c_express like", value, "cExpress");
            return (Criteria) this;
        }

        public Criteria andCExpressNotLike(String value) {
            addCriterion("c_express not like", value, "cExpress");
            return (Criteria) this;
        }

        public Criteria andCExpressIn(List<String> values) {
            addCriterion("c_express in", values, "cExpress");
            return (Criteria) this;
        }

        public Criteria andCExpressNotIn(List<String> values) {
            addCriterion("c_express not in", values, "cExpress");
            return (Criteria) this;
        }

        public Criteria andCExpressBetween(String value1, String value2) {
            addCriterion("c_express between", value1, value2, "cExpress");
            return (Criteria) this;
        }

        public Criteria andCExpressNotBetween(String value1, String value2) {
            addCriterion("c_express not between", value1, value2, "cExpress");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table conditions
     *
     * @mbggenerated do_not_delete_during_merge Fri May 03 20:19:35 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table conditions
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}