package com.offcn.pojo;

import java.util.Date;




public class staff {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.staff_id
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    private Integer staffId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.staff_name
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    private String staffName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.gender
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.birthhday
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */

    private Date birthhday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.phone
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff.password
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.staff_id
     *
     * @return the value of staff.staff_id
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public Integer getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.staff_id
     *
     * @param staffId the value for staff.staff_id
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public void setStaffId(Integer staffId) {
        this.staffId = staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.staff_name
     *
     * @return the value of staff.staff_name
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public String getStaffName() {
        return staffName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.staff_name
     *
     * @param staffName the value for staff.staff_name
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public void setStaffName(String staffName) {
        this.staffName = staffName == null ? null : staffName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.gender
     *
     * @return the value of staff.gender
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.gender
     *
     * @param gender the value for staff.gender
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.birthhday
     *
     * @return the value of staff.birthhday
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public Date getBirthhday() {
        return birthhday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.birthhday
     *
     * @param birthhday the value for staff.birthhday
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public void setBirthhday(Date birthhday) {
        this.birthhday = birthhday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.phone
     *
     * @return the value of staff.phone
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.phone
     *
     * @param phone the value for staff.phone
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff.password
     *
     * @return the value of staff.password
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff.password
     *
     * @param password the value for staff.password
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}