package com.offcn.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class waybillExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table waybill
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table waybill
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table waybill
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waybill
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public waybillExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waybill
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waybill
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waybill
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waybill
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waybill
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waybill
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waybill
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waybill
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waybill
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table waybill
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table waybill
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andWaybillIdIsNull() {
            addCriterion("waybill_id is null");
            return (Criteria) this;
        }

        public Criteria andWaybillIdIsNotNull() {
            addCriterion("waybill_id is not null");
            return (Criteria) this;
        }

        public Criteria andWaybillIdEqualTo(String value) {
            addCriterion("waybill_id =", value, "waybillId");
            return (Criteria) this;
        }

        public Criteria andWaybillIdNotEqualTo(String value) {
            addCriterion("waybill_id <>", value, "waybillId");
            return (Criteria) this;
        }

        public Criteria andWaybillIdGreaterThan(String value) {
            addCriterion("waybill_id >", value, "waybillId");
            return (Criteria) this;
        }

        public Criteria andWaybillIdGreaterThanOrEqualTo(String value) {
            addCriterion("waybill_id >=", value, "waybillId");
            return (Criteria) this;
        }

        public Criteria andWaybillIdLessThan(String value) {
            addCriterion("waybill_id <", value, "waybillId");
            return (Criteria) this;
        }

        public Criteria andWaybillIdLessThanOrEqualTo(String value) {
            addCriterion("waybill_id <=", value, "waybillId");
            return (Criteria) this;
        }

        public Criteria andWaybillIdLike(String value) {
            addCriterion("waybill_id like", value, "waybillId");
            return (Criteria) this;
        }

        public Criteria andWaybillIdNotLike(String value) {
            addCriterion("waybill_id not like", value, "waybillId");
            return (Criteria) this;
        }

        public Criteria andWaybillIdIn(List<String> values) {
            addCriterion("waybill_id in", values, "waybillId");
            return (Criteria) this;
        }

        public Criteria andWaybillIdNotIn(List<String> values) {
            addCriterion("waybill_id not in", values, "waybillId");
            return (Criteria) this;
        }

        public Criteria andWaybillIdBetween(String value1, String value2) {
            addCriterion("waybill_id between", value1, value2, "waybillId");
            return (Criteria) this;
        }

        public Criteria andWaybillIdNotBetween(String value1, String value2) {
            addCriterion("waybill_id not between", value1, value2, "waybillId");
            return (Criteria) this;
        }

        public Criteria andSProIsNull() {
            addCriterion("s_pro is null");
            return (Criteria) this;
        }

        public Criteria andSProIsNotNull() {
            addCriterion("s_pro is not null");
            return (Criteria) this;
        }

        public Criteria andSProEqualTo(String value) {
            addCriterion("s_pro =", value, "sPro");
            return (Criteria) this;
        }

        public Criteria andSProNotEqualTo(String value) {
            addCriterion("s_pro <>", value, "sPro");
            return (Criteria) this;
        }

        public Criteria andSProGreaterThan(String value) {
            addCriterion("s_pro >", value, "sPro");
            return (Criteria) this;
        }

        public Criteria andSProGreaterThanOrEqualTo(String value) {
            addCriterion("s_pro >=", value, "sPro");
            return (Criteria) this;
        }

        public Criteria andSProLessThan(String value) {
            addCriterion("s_pro <", value, "sPro");
            return (Criteria) this;
        }

        public Criteria andSProLessThanOrEqualTo(String value) {
            addCriterion("s_pro <=", value, "sPro");
            return (Criteria) this;
        }

        public Criteria andSProLike(String value) {
            addCriterion("s_pro like", value, "sPro");
            return (Criteria) this;
        }

        public Criteria andSProNotLike(String value) {
            addCriterion("s_pro not like", value, "sPro");
            return (Criteria) this;
        }

        public Criteria andSProIn(List<String> values) {
            addCriterion("s_pro in", values, "sPro");
            return (Criteria) this;
        }

        public Criteria andSProNotIn(List<String> values) {
            addCriterion("s_pro not in", values, "sPro");
            return (Criteria) this;
        }

        public Criteria andSProBetween(String value1, String value2) {
            addCriterion("s_pro between", value1, value2, "sPro");
            return (Criteria) this;
        }

        public Criteria andSProNotBetween(String value1, String value2) {
            addCriterion("s_pro not between", value1, value2, "sPro");
            return (Criteria) this;
        }

        public Criteria andSCityIsNull() {
            addCriterion("s_city is null");
            return (Criteria) this;
        }

        public Criteria andSCityIsNotNull() {
            addCriterion("s_city is not null");
            return (Criteria) this;
        }

        public Criteria andSCityEqualTo(String value) {
            addCriterion("s_city =", value, "sCity");
            return (Criteria) this;
        }

        public Criteria andSCityNotEqualTo(String value) {
            addCriterion("s_city <>", value, "sCity");
            return (Criteria) this;
        }

        public Criteria andSCityGreaterThan(String value) {
            addCriterion("s_city >", value, "sCity");
            return (Criteria) this;
        }

        public Criteria andSCityGreaterThanOrEqualTo(String value) {
            addCriterion("s_city >=", value, "sCity");
            return (Criteria) this;
        }

        public Criteria andSCityLessThan(String value) {
            addCriterion("s_city <", value, "sCity");
            return (Criteria) this;
        }

        public Criteria andSCityLessThanOrEqualTo(String value) {
            addCriterion("s_city <=", value, "sCity");
            return (Criteria) this;
        }

        public Criteria andSCityLike(String value) {
            addCriterion("s_city like", value, "sCity");
            return (Criteria) this;
        }

        public Criteria andSCityNotLike(String value) {
            addCriterion("s_city not like", value, "sCity");
            return (Criteria) this;
        }

        public Criteria andSCityIn(List<String> values) {
            addCriterion("s_city in", values, "sCity");
            return (Criteria) this;
        }

        public Criteria andSCityNotIn(List<String> values) {
            addCriterion("s_city not in", values, "sCity");
            return (Criteria) this;
        }

        public Criteria andSCityBetween(String value1, String value2) {
            addCriterion("s_city between", value1, value2, "sCity");
            return (Criteria) this;
        }

        public Criteria andSCityNotBetween(String value1, String value2) {
            addCriterion("s_city not between", value1, value2, "sCity");
            return (Criteria) this;
        }

        public Criteria andEProIsNull() {
            addCriterion("e_pro is null");
            return (Criteria) this;
        }

        public Criteria andEProIsNotNull() {
            addCriterion("e_pro is not null");
            return (Criteria) this;
        }

        public Criteria andEProEqualTo(String value) {
            addCriterion("e_pro =", value, "ePro");
            return (Criteria) this;
        }

        public Criteria andEProNotEqualTo(String value) {
            addCriterion("e_pro <>", value, "ePro");
            return (Criteria) this;
        }

        public Criteria andEProGreaterThan(String value) {
            addCriterion("e_pro >", value, "ePro");
            return (Criteria) this;
        }

        public Criteria andEProGreaterThanOrEqualTo(String value) {
            addCriterion("e_pro >=", value, "ePro");
            return (Criteria) this;
        }

        public Criteria andEProLessThan(String value) {
            addCriterion("e_pro <", value, "ePro");
            return (Criteria) this;
        }

        public Criteria andEProLessThanOrEqualTo(String value) {
            addCriterion("e_pro <=", value, "ePro");
            return (Criteria) this;
        }

        public Criteria andEProLike(String value) {
            addCriterion("e_pro like", value, "ePro");
            return (Criteria) this;
        }

        public Criteria andEProNotLike(String value) {
            addCriterion("e_pro not like", value, "ePro");
            return (Criteria) this;
        }

        public Criteria andEProIn(List<String> values) {
            addCriterion("e_pro in", values, "ePro");
            return (Criteria) this;
        }

        public Criteria andEProNotIn(List<String> values) {
            addCriterion("e_pro not in", values, "ePro");
            return (Criteria) this;
        }

        public Criteria andEProBetween(String value1, String value2) {
            addCriterion("e_pro between", value1, value2, "ePro");
            return (Criteria) this;
        }

        public Criteria andEProNotBetween(String value1, String value2) {
            addCriterion("e_pro not between", value1, value2, "ePro");
            return (Criteria) this;
        }

        public Criteria andECityIsNull() {
            addCriterion("e_city is null");
            return (Criteria) this;
        }

        public Criteria andECityIsNotNull() {
            addCriterion("e_city is not null");
            return (Criteria) this;
        }

        public Criteria andECityEqualTo(String value) {
            addCriterion("e_city =", value, "eCity");
            return (Criteria) this;
        }

        public Criteria andECityNotEqualTo(String value) {
            addCriterion("e_city <>", value, "eCity");
            return (Criteria) this;
        }

        public Criteria andECityGreaterThan(String value) {
            addCriterion("e_city >", value, "eCity");
            return (Criteria) this;
        }

        public Criteria andECityGreaterThanOrEqualTo(String value) {
            addCriterion("e_city >=", value, "eCity");
            return (Criteria) this;
        }

        public Criteria andECityLessThan(String value) {
            addCriterion("e_city <", value, "eCity");
            return (Criteria) this;
        }

        public Criteria andECityLessThanOrEqualTo(String value) {
            addCriterion("e_city <=", value, "eCity");
            return (Criteria) this;
        }

        public Criteria andECityLike(String value) {
            addCriterion("e_city like", value, "eCity");
            return (Criteria) this;
        }

        public Criteria andECityNotLike(String value) {
            addCriterion("e_city not like", value, "eCity");
            return (Criteria) this;
        }

        public Criteria andECityIn(List<String> values) {
            addCriterion("e_city in", values, "eCity");
            return (Criteria) this;
        }

        public Criteria andECityNotIn(List<String> values) {
            addCriterion("e_city not in", values, "eCity");
            return (Criteria) this;
        }

        public Criteria andECityBetween(String value1, String value2) {
            addCriterion("e_city between", value1, value2, "eCity");
            return (Criteria) this;
        }

        public Criteria andECityNotBetween(String value1, String value2) {
            addCriterion("e_city not between", value1, value2, "eCity");
            return (Criteria) this;
        }

        public Criteria andSNameIsNull() {
            addCriterion("s_name is null");
            return (Criteria) this;
        }

        public Criteria andSNameIsNotNull() {
            addCriterion("s_name is not null");
            return (Criteria) this;
        }

        public Criteria andSNameEqualTo(String value) {
            addCriterion("s_name =", value, "sName");
            return (Criteria) this;
        }

        public Criteria andSNameNotEqualTo(String value) {
            addCriterion("s_name <>", value, "sName");
            return (Criteria) this;
        }

        public Criteria andSNameGreaterThan(String value) {
            addCriterion("s_name >", value, "sName");
            return (Criteria) this;
        }

        public Criteria andSNameGreaterThanOrEqualTo(String value) {
            addCriterion("s_name >=", value, "sName");
            return (Criteria) this;
        }

        public Criteria andSNameLessThan(String value) {
            addCriterion("s_name <", value, "sName");
            return (Criteria) this;
        }

        public Criteria andSNameLessThanOrEqualTo(String value) {
            addCriterion("s_name <=", value, "sName");
            return (Criteria) this;
        }

        public Criteria andSNameLike(String value) {
            addCriterion("s_name like", value, "sName");
            return (Criteria) this;
        }

        public Criteria andSNameNotLike(String value) {
            addCriterion("s_name not like", value, "sName");
            return (Criteria) this;
        }

        public Criteria andSNameIn(List<String> values) {
            addCriterion("s_name in", values, "sName");
            return (Criteria) this;
        }

        public Criteria andSNameNotIn(List<String> values) {
            addCriterion("s_name not in", values, "sName");
            return (Criteria) this;
        }

        public Criteria andSNameBetween(String value1, String value2) {
            addCriterion("s_name between", value1, value2, "sName");
            return (Criteria) this;
        }

        public Criteria andSNameNotBetween(String value1, String value2) {
            addCriterion("s_name not between", value1, value2, "sName");
            return (Criteria) this;
        }

        public Criteria andSPhoneIsNull() {
            addCriterion("s_phone is null");
            return (Criteria) this;
        }

        public Criteria andSPhoneIsNotNull() {
            addCriterion("s_phone is not null");
            return (Criteria) this;
        }

        public Criteria andSPhoneEqualTo(String value) {
            addCriterion("s_phone =", value, "sPhone");
            return (Criteria) this;
        }

        public Criteria andSPhoneNotEqualTo(String value) {
            addCriterion("s_phone <>", value, "sPhone");
            return (Criteria) this;
        }

        public Criteria andSPhoneGreaterThan(String value) {
            addCriterion("s_phone >", value, "sPhone");
            return (Criteria) this;
        }

        public Criteria andSPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("s_phone >=", value, "sPhone");
            return (Criteria) this;
        }

        public Criteria andSPhoneLessThan(String value) {
            addCriterion("s_phone <", value, "sPhone");
            return (Criteria) this;
        }

        public Criteria andSPhoneLessThanOrEqualTo(String value) {
            addCriterion("s_phone <=", value, "sPhone");
            return (Criteria) this;
        }

        public Criteria andSPhoneLike(String value) {
            addCriterion("s_phone like", value, "sPhone");
            return (Criteria) this;
        }

        public Criteria andSPhoneNotLike(String value) {
            addCriterion("s_phone not like", value, "sPhone");
            return (Criteria) this;
        }

        public Criteria andSPhoneIn(List<String> values) {
            addCriterion("s_phone in", values, "sPhone");
            return (Criteria) this;
        }

        public Criteria andSPhoneNotIn(List<String> values) {
            addCriterion("s_phone not in", values, "sPhone");
            return (Criteria) this;
        }

        public Criteria andSPhoneBetween(String value1, String value2) {
            addCriterion("s_phone between", value1, value2, "sPhone");
            return (Criteria) this;
        }

        public Criteria andSPhoneNotBetween(String value1, String value2) {
            addCriterion("s_phone not between", value1, value2, "sPhone");
            return (Criteria) this;
        }

        public Criteria andSAddressIsNull() {
            addCriterion("s_address is null");
            return (Criteria) this;
        }

        public Criteria andSAddressIsNotNull() {
            addCriterion("s_address is not null");
            return (Criteria) this;
        }

        public Criteria andSAddressEqualTo(String value) {
            addCriterion("s_address =", value, "sAddress");
            return (Criteria) this;
        }

        public Criteria andSAddressNotEqualTo(String value) {
            addCriterion("s_address <>", value, "sAddress");
            return (Criteria) this;
        }

        public Criteria andSAddressGreaterThan(String value) {
            addCriterion("s_address >", value, "sAddress");
            return (Criteria) this;
        }

        public Criteria andSAddressGreaterThanOrEqualTo(String value) {
            addCriterion("s_address >=", value, "sAddress");
            return (Criteria) this;
        }

        public Criteria andSAddressLessThan(String value) {
            addCriterion("s_address <", value, "sAddress");
            return (Criteria) this;
        }

        public Criteria andSAddressLessThanOrEqualTo(String value) {
            addCriterion("s_address <=", value, "sAddress");
            return (Criteria) this;
        }

        public Criteria andSAddressLike(String value) {
            addCriterion("s_address like", value, "sAddress");
            return (Criteria) this;
        }

        public Criteria andSAddressNotLike(String value) {
            addCriterion("s_address not like", value, "sAddress");
            return (Criteria) this;
        }

        public Criteria andSAddressIn(List<String> values) {
            addCriterion("s_address in", values, "sAddress");
            return (Criteria) this;
        }

        public Criteria andSAddressNotIn(List<String> values) {
            addCriterion("s_address not in", values, "sAddress");
            return (Criteria) this;
        }

        public Criteria andSAddressBetween(String value1, String value2) {
            addCriterion("s_address between", value1, value2, "sAddress");
            return (Criteria) this;
        }

        public Criteria andSAddressNotBetween(String value1, String value2) {
            addCriterion("s_address not between", value1, value2, "sAddress");
            return (Criteria) this;
        }

        public Criteria andRNameIsNull() {
            addCriterion("r_name is null");
            return (Criteria) this;
        }

        public Criteria andRNameIsNotNull() {
            addCriterion("r_name is not null");
            return (Criteria) this;
        }

        public Criteria andRNameEqualTo(String value) {
            addCriterion("r_name =", value, "rName");
            return (Criteria) this;
        }

        public Criteria andRNameNotEqualTo(String value) {
            addCriterion("r_name <>", value, "rName");
            return (Criteria) this;
        }

        public Criteria andRNameGreaterThan(String value) {
            addCriterion("r_name >", value, "rName");
            return (Criteria) this;
        }

        public Criteria andRNameGreaterThanOrEqualTo(String value) {
            addCriterion("r_name >=", value, "rName");
            return (Criteria) this;
        }

        public Criteria andRNameLessThan(String value) {
            addCriterion("r_name <", value, "rName");
            return (Criteria) this;
        }

        public Criteria andRNameLessThanOrEqualTo(String value) {
            addCriterion("r_name <=", value, "rName");
            return (Criteria) this;
        }

        public Criteria andRNameLike(String value) {
            addCriterion("r_name like", value, "rName");
            return (Criteria) this;
        }

        public Criteria andRNameNotLike(String value) {
            addCriterion("r_name not like", value, "rName");
            return (Criteria) this;
        }

        public Criteria andRNameIn(List<String> values) {
            addCriterion("r_name in", values, "rName");
            return (Criteria) this;
        }

        public Criteria andRNameNotIn(List<String> values) {
            addCriterion("r_name not in", values, "rName");
            return (Criteria) this;
        }

        public Criteria andRNameBetween(String value1, String value2) {
            addCriterion("r_name between", value1, value2, "rName");
            return (Criteria) this;
        }

        public Criteria andRNameNotBetween(String value1, String value2) {
            addCriterion("r_name not between", value1, value2, "rName");
            return (Criteria) this;
        }

        public Criteria andRPhoneIsNull() {
            addCriterion("r_phone is null");
            return (Criteria) this;
        }

        public Criteria andRPhoneIsNotNull() {
            addCriterion("r_phone is not null");
            return (Criteria) this;
        }

        public Criteria andRPhoneEqualTo(String value) {
            addCriterion("r_phone =", value, "rPhone");
            return (Criteria) this;
        }

        public Criteria andRPhoneNotEqualTo(String value) {
            addCriterion("r_phone <>", value, "rPhone");
            return (Criteria) this;
        }

        public Criteria andRPhoneGreaterThan(String value) {
            addCriterion("r_phone >", value, "rPhone");
            return (Criteria) this;
        }

        public Criteria andRPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("r_phone >=", value, "rPhone");
            return (Criteria) this;
        }

        public Criteria andRPhoneLessThan(String value) {
            addCriterion("r_phone <", value, "rPhone");
            return (Criteria) this;
        }

        public Criteria andRPhoneLessThanOrEqualTo(String value) {
            addCriterion("r_phone <=", value, "rPhone");
            return (Criteria) this;
        }

        public Criteria andRPhoneLike(String value) {
            addCriterion("r_phone like", value, "rPhone");
            return (Criteria) this;
        }

        public Criteria andRPhoneNotLike(String value) {
            addCriterion("r_phone not like", value, "rPhone");
            return (Criteria) this;
        }

        public Criteria andRPhoneIn(List<String> values) {
            addCriterion("r_phone in", values, "rPhone");
            return (Criteria) this;
        }

        public Criteria andRPhoneNotIn(List<String> values) {
            addCriterion("r_phone not in", values, "rPhone");
            return (Criteria) this;
        }

        public Criteria andRPhoneBetween(String value1, String value2) {
            addCriterion("r_phone between", value1, value2, "rPhone");
            return (Criteria) this;
        }

        public Criteria andRPhoneNotBetween(String value1, String value2) {
            addCriterion("r_phone not between", value1, value2, "rPhone");
            return (Criteria) this;
        }

        public Criteria andRAddressIsNull() {
            addCriterion("r_address is null");
            return (Criteria) this;
        }

        public Criteria andRAddressIsNotNull() {
            addCriterion("r_address is not null");
            return (Criteria) this;
        }

        public Criteria andRAddressEqualTo(String value) {
            addCriterion("r_address =", value, "rAddress");
            return (Criteria) this;
        }

        public Criteria andRAddressNotEqualTo(String value) {
            addCriterion("r_address <>", value, "rAddress");
            return (Criteria) this;
        }

        public Criteria andRAddressGreaterThan(String value) {
            addCriterion("r_address >", value, "rAddress");
            return (Criteria) this;
        }

        public Criteria andRAddressGreaterThanOrEqualTo(String value) {
            addCriterion("r_address >=", value, "rAddress");
            return (Criteria) this;
        }

        public Criteria andRAddressLessThan(String value) {
            addCriterion("r_address <", value, "rAddress");
            return (Criteria) this;
        }

        public Criteria andRAddressLessThanOrEqualTo(String value) {
            addCriterion("r_address <=", value, "rAddress");
            return (Criteria) this;
        }

        public Criteria andRAddressLike(String value) {
            addCriterion("r_address like", value, "rAddress");
            return (Criteria) this;
        }

        public Criteria andRAddressNotLike(String value) {
            addCriterion("r_address not like", value, "rAddress");
            return (Criteria) this;
        }

        public Criteria andRAddressIn(List<String> values) {
            addCriterion("r_address in", values, "rAddress");
            return (Criteria) this;
        }

        public Criteria andRAddressNotIn(List<String> values) {
            addCriterion("r_address not in", values, "rAddress");
            return (Criteria) this;
        }

        public Criteria andRAddressBetween(String value1, String value2) {
            addCriterion("r_address between", value1, value2, "rAddress");
            return (Criteria) this;
        }

        public Criteria andRAddressNotBetween(String value1, String value2) {
            addCriterion("r_address not between", value1, value2, "rAddress");
            return (Criteria) this;
        }

        public Criteria andPosttimeIsNull() {
            addCriterion("posttime is null");
            return (Criteria) this;
        }

        public Criteria andPosttimeIsNotNull() {
            addCriterion("posttime is not null");
            return (Criteria) this;
        }

        public Criteria andPosttimeEqualTo(Date value) {
            addCriterion("posttime =", value, "posttime");
            return (Criteria) this;
        }

        public Criteria andPosttimeNotEqualTo(Date value) {
            addCriterion("posttime <>", value, "posttime");
            return (Criteria) this;
        }

        public Criteria andPosttimeGreaterThan(Date value) {
            addCriterion("posttime >", value, "posttime");
            return (Criteria) this;
        }

        public Criteria andPosttimeGreaterThanOrEqualTo(Date value) {
            addCriterion("posttime >=", value, "posttime");
            return (Criteria) this;
        }

        public Criteria andPosttimeLessThan(Date value) {
            addCriterion("posttime <", value, "posttime");
            return (Criteria) this;
        }

        public Criteria andPosttimeLessThanOrEqualTo(Date value) {
            addCriterion("posttime <=", value, "posttime");
            return (Criteria) this;
        }

        public Criteria andPosttimeIn(List<Date> values) {
            addCriterion("posttime in", values, "posttime");
            return (Criteria) this;
        }

        public Criteria andPosttimeNotIn(List<Date> values) {
            addCriterion("posttime not in", values, "posttime");
            return (Criteria) this;
        }

        public Criteria andPosttimeBetween(Date value1, Date value2) {
            addCriterion("posttime between", value1, value2, "posttime");
            return (Criteria) this;
        }

        public Criteria andPosttimeNotBetween(Date value1, Date value2) {
            addCriterion("posttime not between", value1, value2, "posttime");
            return (Criteria) this;
        }

        public Criteria andPostpersonIsNull() {
            addCriterion("postperson is null");
            return (Criteria) this;
        }

        public Criteria andPostpersonIsNotNull() {
            addCriterion("postperson is not null");
            return (Criteria) this;
        }

        public Criteria andPostpersonEqualTo(String value) {
            addCriterion("postperson =", value, "postperson");
            return (Criteria) this;
        }

        public Criteria andPostpersonNotEqualTo(String value) {
            addCriterion("postperson <>", value, "postperson");
            return (Criteria) this;
        }

        public Criteria andPostpersonGreaterThan(String value) {
            addCriterion("postperson >", value, "postperson");
            return (Criteria) this;
        }

        public Criteria andPostpersonGreaterThanOrEqualTo(String value) {
            addCriterion("postperson >=", value, "postperson");
            return (Criteria) this;
        }

        public Criteria andPostpersonLessThan(String value) {
            addCriterion("postperson <", value, "postperson");
            return (Criteria) this;
        }

        public Criteria andPostpersonLessThanOrEqualTo(String value) {
            addCriterion("postperson <=", value, "postperson");
            return (Criteria) this;
        }

        public Criteria andPostpersonLike(String value) {
            addCriterion("postperson like", value, "postperson");
            return (Criteria) this;
        }

        public Criteria andPostpersonNotLike(String value) {
            addCriterion("postperson not like", value, "postperson");
            return (Criteria) this;
        }

        public Criteria andPostpersonIn(List<String> values) {
            addCriterion("postperson in", values, "postperson");
            return (Criteria) this;
        }

        public Criteria andPostpersonNotIn(List<String> values) {
            addCriterion("postperson not in", values, "postperson");
            return (Criteria) this;
        }

        public Criteria andPostpersonBetween(String value1, String value2) {
            addCriterion("postperson between", value1, value2, "postperson");
            return (Criteria) this;
        }

        public Criteria andPostpersonNotBetween(String value1, String value2) {
            addCriterion("postperson not between", value1, value2, "postperson");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table waybill
     *
     * @mbggenerated do_not_delete_during_merge Fri May 03 20:19:35 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table waybill
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}