package com.offcn.pojo;
import java.util.Date;




public class waybill {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waybill.waybill_id
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    private String waybillId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waybill.s_pro
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    private String sPro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waybill.s_city
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    private String sCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waybill.e_pro
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    private String ePro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waybill.e_city
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    private String eCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waybill.s_name
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    private String sName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waybill.s_phone
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    private String sPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waybill.s_address
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    private String sAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waybill.r_name
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    private String rName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waybill.r_phone
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    private String rPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waybill.r_address
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    private String rAddress;

   
   
    private Date posttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column waybill.postperson
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    private String postperson;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waybill.waybill_id
     *
     * @return the value of waybill.waybill_id
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public String getWaybillId() {
        return waybillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waybill.waybill_id
     *
     * @param waybillId the value for waybill.waybill_id
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public void setWaybillId(String waybillId) {
        this.waybillId = waybillId == null ? null : waybillId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waybill.s_pro
     *
     * @return the value of waybill.s_pro
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public String getsPro() {
        return sPro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waybill.s_pro
     *
     * @param sPro the value for waybill.s_pro
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public void setsPro(String sPro) {
        this.sPro = sPro == null ? null : sPro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waybill.s_city
     *
     * @return the value of waybill.s_city
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public String getsCity() {
        return sCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waybill.s_city
     *
     * @param sCity the value for waybill.s_city
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public void setsCity(String sCity) {
        this.sCity = sCity == null ? null : sCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waybill.e_pro
     *
     * @return the value of waybill.e_pro
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public String getePro() {
        return ePro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waybill.e_pro
     *
     * @param ePro the value for waybill.e_pro
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public void setePro(String ePro) {
        this.ePro = ePro == null ? null : ePro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waybill.e_city
     *
     * @return the value of waybill.e_city
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public String geteCity() {
        return eCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waybill.e_city
     *
     * @param eCity the value for waybill.e_city
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public void seteCity(String eCity) {
        this.eCity = eCity == null ? null : eCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waybill.s_name
     *
     * @return the value of waybill.s_name
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public String getsName() {
        return sName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waybill.s_name
     *
     * @param sName the value for waybill.s_name
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public void setsName(String sName) {
        this.sName = sName == null ? null : sName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waybill.s_phone
     *
     * @return the value of waybill.s_phone
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public String getsPhone() {
        return sPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waybill.s_phone
     *
     * @param sPhone the value for waybill.s_phone
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public void setsPhone(String sPhone) {
        this.sPhone = sPhone == null ? null : sPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waybill.s_address
     *
     * @return the value of waybill.s_address
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public String getsAddress() {
        return sAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waybill.s_address
     *
     * @param sAddress the value for waybill.s_address
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public void setsAddress(String sAddress) {
        this.sAddress = sAddress == null ? null : sAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waybill.r_name
     *
     * @return the value of waybill.r_name
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public String getrName() {
        return rName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waybill.r_name
     *
     * @param rName the value for waybill.r_name
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public void setrName(String rName) {
        this.rName = rName == null ? null : rName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waybill.r_phone
     *
     * @return the value of waybill.r_phone
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public String getrPhone() {
        return rPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waybill.r_phone
     *
     * @param rPhone the value for waybill.r_phone
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public void setrPhone(String rPhone) {
        this.rPhone = rPhone == null ? null : rPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waybill.r_address
     *
     * @return the value of waybill.r_address
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public String getrAddress() {
        return rAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waybill.r_address
     *
     * @param rAddress the value for waybill.r_address
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public void setrAddress(String rAddress) {
        this.rAddress = rAddress == null ? null : rAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waybill.posttime
     *
     * @return the value of waybill.posttime
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public Date getPosttime() {
        return posttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waybill.posttime
     *
     * @param posttime the value for waybill.posttime
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public void setPosttime(Date posttime) {
        this.posttime = posttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column waybill.postperson
     *
     * @return the value of waybill.postperson
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public String getPostperson() {
        return postperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column waybill.postperson
     *
     * @param postperson the value for waybill.postperson
     *
     * @mbggenerated Fri May 03 20:19:35 CST 2019
     */
    public void setPostperson(String postperson) {
        this.postperson = postperson == null ? null : postperson.trim();
    }
}